### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by niteshgarg** [VideoExpertsGroup/RTSPPlayer#1]
Hi There,

I am trying to integrate the rtsp player and getting below error at time during playback.  This error is only coming after the stream has played for sometime like say after 1-2 minutes. KIndly check. I am trying to play a live stream from IP camera.

10-26 16:32:58.198: E/jni/src/content/ffmpeg_content_provider.c(2036): timeout_interrupt_callback guard time: 120000000, first:1785957233, diff:138319275
10-26 16:32:58.206: E/jni/src/content/ffmpeg_content_provider.c(2036): timeout_interrupt_callback guard time: 120000000, first:1785957233, diff:138330201
10-26 16:32:58.221: E/jni/src/content/ffmpeg_content_provider.c(2036): timeout_interrupt_callback guard time: 120000000, first:1785957233, diff:138344941

**Comment by Xingchen-L** [comment]
i have the same problem, implements MediaPlayer.MediaPlayerCallback, override method Status(int i) , convert int param to enum, and then,  get the play state,invoke player.Open(config, this) again while disconnected. 
@Override
    public int Status(int i) {
        MediaPlayer.PlayerNotifyCodes status = MediaPlayer.PlayerNotifyCodes.forValue(i);
        L.i(TAG, "video status = " + status.toString());
        switch (status) {
            case CP_CONNECT_STARTING:
                handler.sendEmptyMessage(MSG_VIDEO_CONNECT_STARTING);
            case CP_CONNECT_SUCCESSFUL:
                handler.sendEmptyMessage(MSG_VIDEO_CONNECT_SUCCESS);
                break;
            case PLP_BUILD_SUCCESSFUL:
                handler.sendEmptyMessage(MSG_VIDEO_BUILD_SUCCESS);
                break;
            case PLP_PLAY_SUCCESSFUL:
                handler.sendEmptyMessage(MSG_VIDEO_PLAY_SUCCESS);
                break;
            case CP_CONNECT_FAILED:
                handler.sendEmptyMessage(MSG_VIDEO_CONNECT_FAILED);
                break;
            case PLP_BUILD_FAILED:
                handler.sendEmptyMessage(MSG_VIDEO_BUILD_FAILED);
                break;
            case PLP_PLAY_FAILED:
                handler.sendEmptyMessage(MSG_VIDEO_PLAY_FAILED);
            case CP_ERROR_DISCONNECTED:
                handler.sendEmptyMessage(MSG_VIDEO_DISCONNECTED);
                break;
            case CP_ERROR_NODATA_TIMEOUT:
                break;
        }
        return 0;
    }

**Comment by VideoExpertsGroup** [comment]
Hello,



It is not possibly to call Open methon on disconnect message.

Please player.Close(..) before Open .

Please see how CP_ERROR_DISCONNECTED is handled in sample : https://github.com/VideoExpertsGroup/RTSPPlayer



Thanks,

Ivan




---- On Mon, 22 Feb 2016 18:47:54 -1200 XingchenL &lt;notifications@github.com&gt;wrote ---- 




i have the same problem, implements MediaPlayer.MediaPlayerCallback, override method Status(int i) , convert int param to enum, and then, get the play state,invoke player.Open(config, this) again while disconnected. 

 @Override

 public int Status(int i) {

 MediaPlayer.PlayerNotifyCodes status = MediaPlayer.PlayerNotifyCodes.forValue(i);

 L.i(TAG, "video status = " + status.toString());

 switch (status) {

 case CP_CONNECT_STARTING:

 handler.sendEmptyMessage(MSG_VIDEO_CONNECT_STARTING);

 case CP_CONNECT_SUCCESSFUL:

 handler.sendEmptyMessage(MSG_VIDEO_CONNECT_SUCCESS);

 break;

 case PLP_BUILD_SUCCESSFUL:

 handler.sendEmptyMessage(MSG_VIDEO_BUILD_SUCCESS);

 break;

 case PLP_PLAY_SUCCESSFUL:

 handler.sendEmptyMessage(MSG_VIDEO_PLAY_SUCCESS);

 break;

 case CP_CONNECT_FAILED:

 handler.sendEmptyMessage(MSG_VIDEO_CONNECT_FAILED);

 break;

 case PLP_BUILD_FAILED:

 handler.sendEmptyMessage(MSG_VIDEO_BUILD_FAILED);

 break;

 case PLP_PLAY_FAILED:

 handler.sendEmptyMessage(MSG_VIDEO_PLAY_FAILED);

 case CP_ERROR_DISCONNECTED:

 handler.sendEmptyMessage(MSG_VIDEO_DISCONNECTED);

 break;

 case CP_ERROR_NODATA_TIMEOUT:

 break;

 }

 return 0;

 }

**Comment by omazrv** [comment]
I have the same issue, it happens exactly in 2 minutes.
Maybe its some constraint from VideoExpertGroup

**Comment by VideoExpertsGroup** [comment]
Dear omazrv,

This is a trial version, so the playback is limited to 2 minutes.

Regards,
Video Experts Group

**Comment by naitikvithlani** [comment]
Is there any link for full version ?

**Comment by omazrv** [comment]
@naitikvithlani 
Or how we can get full version?

**Comment by naitikvithlani** [comment]
i have registered in veg(Video Experts Group) web site and i got the downloadable link for release SDK.

Thank you

**Comment by omazrv** [comment]
What do u mean the downloadable link for release SDK. Is it full? I mean
does it play forever, not for 2 minutes?

With best wishes, Oleh Mazur

**Comment by naitikvithlani** [comment]
I have just download it, in progress of implementing.

**Comment by omazrv** [comment]
@naitikvithlani 
Ok. Please tell me about your results

**Comment by niteshgarg** [comment]
Closing this issue as this not an issue but as designed. 
I will suggest you to pls continue your discussions offline.

**Comment by VideoExpertsGroup** [comment]
@omazrv @naitikvithlani 
If you would like to get the full version of SDK, please ask for a quote in the email to expert@videoexpertsgroup.com
Thank you.
