### ISSUE TITLE
playe about 2 minute,why pop a string "Demo Version!" and the app stop play.

### ISSUE THREAD

**Issue by welcomeem** [VideoExpertsGroup/RTSPPlayer#12]
playe about 2 minute,why pop a string "Demo Version!" and the app stop play. may be my setting is not right ?

**Comment by VideoExpertsGroup1** [comment]
Dear @welcomeem ,

This is a trial version, so the playback is limited to 2 minutes. Please contact expert@videoexpertsgroup.com to purchase the license.

Regards,
Video Experts Group
