### ISSUE TITLE
Android 5.x

### ISSUE THREAD

**Issue by JohnRSim** [VideoExpertsGroup/RTSPPlayer#2]
Could not get the stream working on my Android Samsung S6 5.1.1 
Stream works on IOS, and desktop vlc..

**Comment by Suradach** [comment]
Could not get the stream working on my Android Samsung S6 5.1.1
Stream works on IOS, and desktop vlc.

**Comment by VideoExpertsGroup1** [comment]
This issue was fixed in the latest version
