### ISSUE TITLE
please tell me how to reduce the delay?

### ISSUE THREAD

**Issue by huangcy3373** [VideoExpertsGroup/RTSPPlayer#5]
the view on android is delay 3s or more slower than the view in pc.

**Comment by VideoExpertsGroup1** [comment]
Please use low latency settings :

conf.setDecodingType( 0 ); // S/W decoder
conf.setConnectionNetworkProtocol( 1 ); // 0 - UDP, 1 - TCP
conf.setSynchroEnable( 0 ); // Disable sync
conf.setDecoderLatency( 1 ); // Low Latency on decoder
conf.setNumberOfCPUCores( 0 ); // Max number of CPU
conf.setConnectionDetectionTime( 1000 );
conf.setConnectionBufferingTime( 0 );

**Comment by huangcy3373** [comment]
yes!  it works , but  i still use : setDecodingType( 1 ); because if i use setDecodingType( 0 ), the video player is not smooth ,and the delay is more.  whatever it works obviously. Thanks
