### ISSUE TITLE
Android_JNI_ThreadDestroyed

### ISSUE THREAD

**Issue by huangcy3373** [VideoExpertsGroup/RTSPPlayer#6]
hi, when i player back the rtsp stream,  player only can play About two minutes and the palyer is closed. do you know the why? thanks

**Comment by VideoExpertsGroup1** [comment]
Dear @huangcy3373,

This is a trial version, so the playback is limited to 2 minutes.
If you would like to get the full version of SDK, please ask for a quote in the email to expert@videoexpertsgroup.com
Thank you.

Regards,
Video Experts Group
