### ISSUE TITLE
Don't play link rtsp

### ISSUE THREAD

**Issue by nguyenthoai** [VideoExpertsGroup/RTSPPlayer#8]
link: rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/definst/mp4:bigbuckbunnyiphone_400.mp4

**Comment by VideoExpertsGroup1** [comment]
Hi @nguyenthoai 
This link is working in the demo app

Regards,
VXG Team

**Comment by Nicepose** [comment]
@nguyenthoai  what kind of problem do you have?
